### ISSUE TITLE
Importing Azure Working Environment fails with "Missing X-Agent-Id"

### ISSUE THREAD

**Issue by felix-melligan** [NetApp/terraform-provider-netapp-cloudmanager#71]
Command run:
shell>>:Prod felixmelligan$ terraform import 'netapp-cloudmanager_cvo_azure.cl-azure[0]' VsaWorkingEnvironment-wDPK77mG
netapp-cloudmanager_cvo_azure.cl-azure[0]: Importing from ID "VsaWorkingEnvironment-wDPK77mG"...
netapp-cloudmanager_cvo_azure.cl-azure[0]: Import prepared!
  Prepared netapp-cloudmanager_cvo_azure for import
netapp-cloudmanager_cvo_azure.cl-azure[0]: Refreshing state... [id=VsaWorkingEnvironment-wDPK77mG]

Error: code: 400, message: Missing X-Agent-Id header

Looks like we need to specify the clientID of the connector but I'm not sure where?

Thanks!

**Comment by wenjun666** [comment]
We are thinking of disabling the import function for cvo Azure because there are many attributes only exist in creation. It's impossible to retrieve all attributes, which lead to potential risk of misrepresenting the current state of actual environment. As an alternative, we can have a data source cvo azure. Please let me know if that will serve your need.
